### ISSUE TITLE
Symlink'ed files deployment with 6.0.0?

### ISSUE THREAD

**Issue by ghybs** [XervoIO/cli#123]
Hi,

I just switched to Modulus-CLI version 6.0.0 and figured out I now have to use the Meteor runtime in Modulus.
I am happy the new deployment process performs demeteorization server-side, so it takes much less network usage.

But it seems the code sent to the server does not contain symlink'ed files, therefore it can no longer access my private npm repositories in `node_modules` root folder (it could be any arbitrary path actually).

**Please is there an easy command to make the deploy tool send symlink'ed files as well?**

In 5.x the demeteorization was done on my machine, so it could access symlink'ed files as if they were standard files.

Thank you in advance for your precious help!

**Comment by ghybs** [comment]
To be more specific, it looks like symbolic links to direct files **do work**, but not if the symbolic link is on a parent folder.

**Comment by kvo68** [comment]
Any solution to this issue?  I encountered this with the latest modulus cli version 6.5.  My project, with symlinks to local packages works fine locally but when I tried to "modulus deploy", got this error:

While selecting package versions:
error: unknown package in top-level dependencies: xxx
unknown package in top-level dependencies: yyy

**Comment by kvo68** [comment]
Similar discussion here: Is it possible to use packages from a package folder outside of the app folder? #109

**Comment by jackboberg** [comment]
@kvo68 Thanks for reviving this issue, I will try to look into some solutions. I believe the relevant code would be [here](https://github.com/XervoIO/cli/blob/master/lib/controllers/project.js#L669).

In #109, the issue seems to be relative paths that are defined in code, so I doubt a single fix will address both problems..

**Comment by ghybs** [comment]
Closing due to Xervo service shut down :-(
