### ISSUE TITLE
Dependency doesn't exists

### ISSUE THREAD

**Issue by mobiglas** [XervoIO/cli#166]
Hello, I tried to install the CLI but I ran into this error

> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@xervo/cli"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code E404
npm ERR! 404 Not found : @xervo/api-util
npm ERR! 404 
npm ERR! 404  '@xervo/api-util' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@xervo/cli'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

In the package.json there is a dependency " "@xervo/api-util": "0.2.0"," which cannot be found in the NPM https://www.npmjs.com/search?q=%20@xervo&page=1&ranking=optimal

The dependecy was added 22 days ago, and modified 11 days ago from what I can see https://github.com/XervoIO/cli/blame/edfec73cb1dcc2581d81d620e9bdc5f4de481e70/package.json

Am I doing something wrong? Thanks.

**Comment by bsatrom** [comment]
Thanks for the heads up, that dependency is now public as well, so you should be able to install the CLI
